algoritmo "Meu Nome"
// Disciplina  :  [Linguagem e Lógica de Programação]
// Descrição   : 2) Faça um programa que leia o nome de uma pessoa e mostre uma mensagem de boas-vindas para ela:
// Autor(a)    : DEBORA DA SILVA CORREIA
// Data atual  : 24/08/2025
var
    Nome : caractere
inicio
    escreva ("Qual é o seu nome: ")
    leia (nome)
    escreva ("Olá, ", nome, " é um prazer te conhecer !")
fimalgoritmo