algoritmo "MeuNome"
// Disciplina  :  [Linguagem e Lógica de Programação]
// Professor   : [Nome do Professor]
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : DATA_ATUAL/MES_ATUAL/ANO_ATUAL
var
Nome : caractere

inicio

escreva ("Qual é o seu nome: ")
leia (nome)
escreva ("Olá, ", nome, " é um prazer te conhecer !")

fimalgoritmo