algoritmo "NomeSalario"
// Disciplina  :  [Linguagem e Lógica de Programação]
// Professor   : [Nome do Professor]
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : DATA_ATUAL/MES_ATUAL/ANO_ATUAL
var

nome: caractere
sal: real

inicio

escreva ("Digite seu nome completo: ")
leia (nome)
escreva ("qual o seu salario? ")
leia (sal)
escreva ("O funcionario ", nome, " tem um salario de R$", SAL, " em Junho.")

fimalgoritmo