algoritmo "Calculo"
// Disciplina  :  [Linguagem e Lógica de Programação]
// Professor   : [Nome do Professor]
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : DATA_ATUAL/MES_ATUAL/ANO_ATUAL
var

n1, n2, s, m: real

inicio
escreva("Digite a nota 1: ")
leia(n1)
escreva ("Digite a nota 2: ")
leia (n2)
s <- n1 + n2
m <- s / 2 
escreva ("A soma entre ", n1, " e ", n2, " é de ", s, ". E a média é de ", m)

fimalgoritmo