algoritmo "AntecessorSucessor"
// Disciplina  :  [Linguagem e Lógica de Programação]
// Professor   : [Nome do Professor]
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : DATA_ATUAL/MES_ATUAL/ANO_ATUAL
var

num, ant, suc: inteiro

inicio

escreva ("Digite um numero: ")
leia (num)
ant<-num-1
suc<-num+1
escreval ("O antecessor de ", num, " é ", ant)
escreval ("O sucessor de ", num, " é ", suc)

fimalgoritmo