algoritmo "Dobro e um Terço"
// Disciplina  :  [Linguagem e Lógica de Programação]
// Descrição   : 7) Crie um algoritmo que leia um número real e mostre na tela o seu dobro e a sua terça parte.
// Autor(a)    : DEBORA DA SILVA CORREIA
// Data atual  : 24/08/2025
var
    num, dub, ter: real
inicio
    escreva ("type a number: ")
    leia (num)
    dub<- num*2
    ter<- num/3
    escreval ("The double of ", num, " is ", dub)
    escreval ("The third part of ", num, " is ", ter)
fimalgoritmo