algoritmo "dobro_1terco"
// Disciplina  :  [Linguagem e Lógica de Programação]
// Professor   : [Nome do Professor]
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : DATA_ATUAL/MES_ATUAL/ANO_ATUAL
var

num, dub, ter: real

inicio

escreva ("type a number: ")
leia (num)
dub<- num*2
ter<- num/3
escreval ("The double of ", num, " is ", dub)
escreval ("The third part of ", num, " is ", ter)

fimalgoritmo