algoritmo "38 contagem"
// Disciplina  :  [Linguagem e Lógica de Programação]
// Descrição   : 38) Escreva um programa que mostre na tela a seguinte contagem:
//                  6 7 8 9 10 11 Acabou!
// Autor(a)    : DEBORA DA SILVA CORREIA
// Data atual  : 24/08/2025
var
    cont:inteiro
inicio
    cont<-6
    enquanto ((cont>=6) e (cont<=11)) faca
        escreva (cont, " ")
        cont<-cont+1
    fimenquanto
    escreva("ACABOU!")
fimalgoritmo