algoritmo "38 contagem"
// Disciplina  :  [Linguagem e Lógica de Programação]
// Professor   : [Nome do Professor]
// Descrição   : 38) Escreva um programa que mostre na tela a seguinte contagem:
//                  6 7 8 9 10 11 Acabou!
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : DATA_ATUAL/MES_ATUAL/ANO_ATUAL
var

cont:inteiro

inicio
cont<-6
enquanto ((cont>=6) e (cont<=11)) faca
    escreva (cont, " ")
    cont<-cont+1
fimenquanto
escreva("ACABOU!")

fimalgoritmo