algoritmo "39. CONTAGEM"
// Disciplina  :  [Linguagem e Lógica de Programação]
// Descrição   : 39) Faça um algoritmo que mostre na tela a seguinte contagem:
//                  10 9 8 7 6 5 4 3 Acabou!
// Autor(a)    : DEBORA DA SILVA CORREIA
// Data atual  : 24/08/2025
var
    cont:inteiro
inicio
    cont<-10
    enquanto ((cont>=3) e (cont<=10)) faca
        escreva (cont, " ")
        cont<-cont-1
    fimenquanto
    escreva("ACABOU!")
fimalgoritmo