algoritmo "39. CONTAGEM"
// Disciplina  :  [Linguagem e Lógica de Programação]
// Professor   : [Nome do Professor]
// Descrição   : 39) Faça um algoritmo que mostre na tela a seguinte contagem:
//                  10 9 8 7 6 5 4 3 Acabou!
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : DATA_ATUAL/MES_ATUAL/ANO_ATUAL
var

cont:inteiro

inicio
cont<-10
enquanto ((cont>=3) e (cont<=10)) faca
    escreva (cont, " ")
    cont<-cont-1
fimenquanto
escreva("ACABOU!")

fimalgoritmo