algoritmo "Nome do Programa"
// Disciplina  :  [Linguagem e Lógica de Programação]
// Professor   : [Nome do Professor]
// Descrição   : 40) Crie um aplicativo que mostre na tela a seguinte contagem:
//                      0 3 6 9 12 15 18 Acabou!
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : DATA_ATUAL/MES_ATUAL/ANO_ATUAL
var

CONT: INTEIRO

inicio

CONT<-0
enquanto (CONT<20) faca
    escreva (CONT, " ")
    CONT<-CONT+3
fimenquanto
escreval ("ACABOU!")
fimalgoritmo