algoritmo "Contagem Enquanto"
// Disciplina  :  [Linguagem e Lógica de Programação]
// Descrição   : 40) Crie um aplicativo que mostre na tela a seguinte contagem:
//                      0 3 6 9 12 15 18 Acabou!
// Autor(a)    : DEBORA DA SILVA CORREIA
// Data atual  : 24/08/2025
var
    CONT: INTEIRO
inicio
    CONT<-0
    enquanto (CONT<20) faca
        escreva (CONT, " ")
        CONT<-CONT+3
    fimenquanto
    escreval ("ACABOU!")
fimalgoritmo