algoritmo "64"
// Disciplina  :  [Linguagem e Lógica de Programação]
// Professor   : [Nome do Professor]
// Descrição   : 64) Desenvolva um programa usando a estrutura “para” que mostre na tela a seguinte contagem:
//                              0 5 10 15 20 25 30 35 40 Acabou!
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : DATA_ATUAL/MES_ATUAL/ANO_ATUAL
var

CONT:INTEIRO

inicio

para CONT de 0 ate 40 passo 5 faca
    escreva (CONT, " ")
fimpara
escreva(" Acabou!")

fimalgoritmo