algoritmo "64 Contagem Para"
// Disciplina  :  [Linguagem e Lógica de Programação]
// Descrição   : 64) Desenvolva um programa usando a estrutura “para” que mostre na tela a seguinte contagem:
//                              0 5 10 15 20 25 30 35 40 Acabou!
// Autor(a)    : DEBORA DA SILVA CORREIA
// Data atual  : 24/08/2025
var
    CONT:INTEIRO
inicio
    para CONT de 0 ate 40 passo 5 faca
        escreva (CONT, " ")
    fimpara
    escreva(" Acabou!")
fimalgoritmo