algoritmo "65 Contagem Para"
// Disciplina  :  [Linguagem e Lógica de Programação]
// Descrição   : 65) Desenvolva um programa usando a estrutura “para” que mostre na tela a seguinte contagem:
//                          100 90 80 70 60 50 40 30 20 10 0 Acabou!
// Autor(a)    : DEBORA DA SILVA CORREIA
// Data atual  : 24/08/2025
var
    cont: INTEIRO
inicio
    para cont de 100 ate 0 passo -10 faca
        escreva (cont, " ")
    fimpara
    escreva("ACABOU!")
fimalgoritmo