algoritmo "operadores logicos e relacionais"
// Disciplina  :  [Linguagem e Lógica de Programação]
// Descrição   : Teste de operadores logicos e relacionais. Tarefa da Aula 4 do Curso em Video
// Autor(a)    : DEBORA DA SILVA CORREIA
// Data atual  : 24/08/2025
var
    A, B, C: inteiro
inicio
    A <- 2
    B<- 3
    C <- 5
    escreval (A>B)
    escreval (A>2)
    escreval (A>=2)
    escreval (c=a+b)
    escreval (c>=b^a)
    escreval (b<=c%2)
    escreval (1=c%2)
fimalgoritmo