algoritmo "Conta Negativos"
// Disciplina  :  [Linguagem e Lógica de Programação]
// Descrição   : Tarefa da aula 10 do Curso em Video
// Autor(a)    : DEBORA DA SILVA CORREIA
// Data atual  : 24/08/2025
Var
    n, c, TotN:inteiro
inicio
    C<-1
    repita
        escreva("Digite um numero: ")
        leia(n)
        se (N<0) entao
            TotN<-TotN+1
        fimse
        c<-c+1
    ate (c>5)
    escreval("Foram digitados ", totn, " valores negativos.")
fimalgoritmo